-- AlterTable
ALTER TABLE `Post` ADD COLUMN `category` ENUM('NEWS', 'TRANSFERS', 'OFF_THE_PITCH', 'PREMIER_LEAGUE', 'LA_LIGA', 'BUNDESLIGA', 'SERIE_A') NOT NULL DEFAULT 'NEWS',
    ADD COLUMN `image` VARCHAR(191) NULL,
    ADD COLUMN `imageAlt` VARCHAR(191) NULL;
